--To create, insert, update, delete in MCQQUESTIONS table
DROP TABLE IF EXISTS MCQQUESTIONS;
CREATE TABLE MCQQUESTIONS (ID LONG AUTO_INCREMENT, CONTENT VARCHAR(255) NOT NULL, DIFFICULTY INT NOT NULL);
INSERT INTO MCQQUESTIONS (CONTENT, DIFFICULTY) VALUES ('What is JDBC for?', 3);
INSERT INTO MCQQUESTIONS (CONTENT, DIFFICULTY) VALUES ('What is Java?', 2);
INSERT INTO MCQQUESTIONS (CONTENT, DIFFICULTY) VALUES ('What is H2 database?', 4);
SELECT * FROM MCQQUESTIONS;

UPDATE MCQQUESTIONS SET DIFFICULTY = 1 WHERE ID = 2;		--To update the difficulty of the question which has id = 2

DELETE FROM MCQQUESTIONS WHERE DIFFICULTY = 4;				--To delete all questions having difficulty = 4 from MCQQUESTIONS table